[package]
name = "lbr-server"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

[dependencies]
dbus = "0.8.3"
anyhow = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex-serde = "0.1.0"
open = "1.3.3"
