[package]
name = "librarian-core"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
hex = { version = "0.4.2", features = ["serde"] }
blake3 = "0.3.4"
